# Generated by Django 5.1.4 on 2024-12-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='clase',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=models.TextField(max_length=200),
        ),
    ]
