# Generated by Django 5.1.4 on 2024-12-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_solution_clase_alter_solution_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=models.TextField(max_length=800),
        ),
    ]
