# Generated by Django 5.1.4 on 2024-12-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_alter_solution_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=models.TextField(max_length=1500),
        ),
    ]
