# Generated by Django 5.1.4 on 2025-01-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_solution_dislikes_solution_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
